const kabupaten = [
  {
    id: 1101,
    provinceId: 11,
    name: "KABUPATEN SIMEULUE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1102,
    provinceId: 11,
    name: "KABUPATEN ACEH SINGKIL",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1103,
    provinceId: 11,
    name: "KABUPATEN ACEH SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1104,
    provinceId: 11,
    name: "KABUPATEN ACEH TENGGARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1105,
    provinceId: 11,
    name: "KABUPATEN ACEH TIMUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1106,
    provinceId: 11,
    name: "KABUPATEN ACEH TENGAH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1107,
    provinceId: 11,
    name: "KABUPATEN ACEH BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1108,
    provinceId: 11,
    name: "KABUPATEN ACEH BESAR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1109,
    provinceId: 11,
    name: "KABUPATEN PIDIE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1110,
    provinceId: 11,
    name: "KABUPATEN BIREUEN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1111,
    provinceId: 11,
    name: "KABUPATEN ACEH UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1112,
    provinceId: 11,
    name: "KABUPATEN ACEH BARAT DAYA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1113,
    provinceId: 11,
    name: "KABUPATEN GAYO LUES",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1114,
    provinceId: 11,
    name: "KABUPATEN ACEH TAMIANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1115,
    provinceId: 11,
    name: "KABUPATEN NAGAN RAYA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1116,
    provinceId: 11,
    name: "KABUPATEN ACEH JAYA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1117,
    provinceId: 11,
    name: "KABUPATEN BENER MERIAH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1118,
    provinceId: 11,
    name: "KABUPATEN PIDIE JAYA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1171,
    provinceId: 11,
    name: "KOTA BANDA ACEH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1172,
    provinceId: 11,
    name: "KOTA SABANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1173,
    provinceId: 11,
    name: "KOTA LANGSA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1174,
    provinceId: 11,
    name: "KOTA LHOKSEUMAWE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1175,
    provinceId: 11,
    name: "KOTA SUBULUSSALAM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1201,
    provinceId: 12,
    name: "KABUPATEN NIAS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1202,
    provinceId: 12,
    name: "KABUPATEN MANDAILING NATAL",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1203,
    provinceId: 12,
    name: "KABUPATEN TAPANULI SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1204,
    provinceId: 12,
    name: "KABUPATEN TAPANULI TENGAH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1205,
    provinceId: 12,
    name: "KABUPATEN TAPANULI UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1206,
    provinceId: 12,
    name: "KABUPATEN TOBA SAMOSIR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1207,
    provinceId: 12,
    name: "KABUPATEN LABUHAN BATU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1208,
    provinceId: 12,
    name: "KABUPATEN ASAHAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1209,
    provinceId: 12,
    name: "KABUPATEN SIMALUNGUN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1210,
    provinceId: 12,
    name: "KABUPATEN DAIRI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1211,
    provinceId: 12,
    name: "KABUPATEN KARO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1212,
    provinceId: 12,
    name: "KABUPATEN DELI SERDANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1213,
    provinceId: 12,
    name: "KABUPATEN LANGKAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1214,
    provinceId: 12,
    name: "KABUPATEN NIAS SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1215,
    provinceId: 12,
    name: "KABUPATEN HUMBANG HASUNDUTAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1216,
    provinceId: 12,
    name: "KABUPATEN PAKPAK BHARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1217,
    provinceId: 12,
    name: "KABUPATEN SAMOSIR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1218,
    provinceId: 12,
    name: "KABUPATEN SERDANG BEDAGAI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1219,
    provinceId: 12,
    name: "KABUPATEN BATU BARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1220,
    provinceId: 12,
    name: "KABUPATEN PADANG LAWAS UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1221,
    provinceId: 12,
    name: "KABUPATEN PADANG LAWAS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1222,
    provinceId: 12,
    name: "KABUPATEN LABUHAN BATU SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1223,
    provinceId: 12,
    name: "KABUPATEN LABUHAN BATU UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1224,
    provinceId: 12,
    name: "KABUPATEN NIAS UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1225,
    provinceId: 12,
    name: "KABUPATEN NIAS BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1271,
    provinceId: 12,
    name: "KOTA SIBOLGA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1272,
    provinceId: 12,
    name: "KOTA TANJUNG BALAI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1273,
    provinceId: 12,
    name: "KOTA PEMATANG SIANTAR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1274,
    provinceId: 12,
    name: "KOTA TEBING TINGGI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1275,
    provinceId: 12,
    name: "KOTA MEDAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1276,
    provinceId: 12,
    name: "KOTA BINJAI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1277,
    provinceId: 12,
    name: "KOTA PADANGSIDIMPUAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1278,
    provinceId: 12,
    name: "KOTA GUNUNGSITOLI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1301,
    provinceId: 13,
    name: "KABUPATEN KEPULAUAN MENTAWAI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1302,
    provinceId: 13,
    name: "KABUPATEN PESISIR SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1303,
    provinceId: 13,
    name: "KABUPATEN SOLOK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1304,
    provinceId: 13,
    name: "KABUPATEN SIJUNJUNG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1305,
    provinceId: 13,
    name: "KABUPATEN TANAH DATAR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1306,
    provinceId: 13,
    name: "KABUPATEN PADANG PARIAMAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1307,
    provinceId: 13,
    name: "KABUPATEN AGAM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1308,
    provinceId: 13,
    name: "KABUPATEN LIMA PULUH KOTA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1309,
    provinceId: 13,
    name: "KABUPATEN PASAMAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1310,
    provinceId: 13,
    name: "KABUPATEN SOLOK SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1311,
    provinceId: 13,
    name: "KABUPATEN DHARMASRAYA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1312,
    provinceId: 13,
    name: "KABUPATEN PASAMAN BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1371,
    provinceId: 13,
    name: "KOTA PADANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1372,
    provinceId: 13,
    name: "KOTA SOLOK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1373,
    provinceId: 13,
    name: "KOTA SAWAH LUNTO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1374,
    provinceId: 13,
    name: "KOTA PADANG PANJANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1375,
    provinceId: 13,
    name: "KOTA BUKITTINGGI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1376,
    provinceId: 13,
    name: "KOTA PAYAKUMBUH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1377,
    provinceId: 13,
    name: "KOTA PARIAMAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1401,
    provinceId: 14,
    name: "KABUPATEN KUANTAN SINGINGI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1402,
    provinceId: 14,
    name: "KABUPATEN INDRAGIRI HULU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1403,
    provinceId: 14,
    name: "KABUPATEN INDRAGIRI HILIR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1404,
    provinceId: 14,
    name: "KABUPATEN PELALAWAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1405,
    provinceId: 14,
    name: "KABUPATEN S I A K",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1406,
    provinceId: 14,
    name: "KABUPATEN KAMPAR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1407,
    provinceId: 14,
    name: "KABUPATEN ROKAN HULU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1408,
    provinceId: 14,
    name: "KABUPATEN BENGKALIS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1409,
    provinceId: 14,
    name: "KABUPATEN ROKAN HILIR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1410,
    provinceId: 14,
    name: "KABUPATEN KEPULAUAN MERANTI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1471,
    provinceId: 14,
    name: "KOTA PEKANBARU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1473,
    provinceId: 14,
    name: "KOTA D U M A I",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1501,
    provinceId: 15,
    name: "KABUPATEN KERINCI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1502,
    provinceId: 15,
    name: "KABUPATEN MERANGIN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1503,
    provinceId: 15,
    name: "KABUPATEN SAROLANGUN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1504,
    provinceId: 15,
    name: "KABUPATEN BATANG HARI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1505,
    provinceId: 15,
    name: "KABUPATEN MUARO JAMBI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1506,
    provinceId: 15,
    name: "KABUPATEN TANJUNG JABUNG TIMUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1507,
    provinceId: 15,
    name: "KABUPATEN TANJUNG JABUNG BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1508,
    provinceId: 15,
    name: "KABUPATEN TEBO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1509,
    provinceId: 15,
    name: "KABUPATEN BUNGO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1571,
    provinceId: 15,
    name: "KOTA JAMBI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1572,
    provinceId: 15,
    name: "KOTA SUNGAI PENUH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1601,
    provinceId: 16,
    name: "KABUPATEN OGAN KOMERING ULU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1602,
    provinceId: 16,
    name: "KABUPATEN OGAN KOMERING ILIR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1603,
    provinceId: 16,
    name: "KABUPATEN MUARA ENIM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1604,
    provinceId: 16,
    name: "KABUPATEN LAHAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1605,
    provinceId: 16,
    name: "KABUPATEN MUSI RAWAS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1606,
    provinceId: 16,
    name: "KABUPATEN MUSI BANYUASIN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1607,
    provinceId: 16,
    name: "KABUPATEN BANYU ASIN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1608,
    provinceId: 16,
    name: "KABUPATEN OGAN KOMERING ULU SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1609,
    provinceId: 16,
    name: "KABUPATEN OGAN KOMERING ULU TIMUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1610,
    provinceId: 16,
    name: "KABUPATEN OGAN ILIR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1611,
    provinceId: 16,
    name: "KABUPATEN EMPAT LAWANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1612,
    provinceId: 16,
    name: "KABUPATEN PENUKAL ABAB LEMATANG ILIR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1613,
    provinceId: 16,
    name: "KABUPATEN MUSI RAWAS UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1671,
    provinceId: 16,
    name: "KOTA PALEMBANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1672,
    provinceId: 16,
    name: "KOTA PRABUMULIH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1673,
    provinceId: 16,
    name: "KOTA PAGAR ALAM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1674,
    provinceId: 16,
    name: "KOTA LUBUKLINGGAU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1701,
    provinceId: 17,
    name: "KABUPATEN BENGKULU SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1702,
    provinceId: 17,
    name: "KABUPATEN REJANG LEBONG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1703,
    provinceId: 17,
    name: "KABUPATEN BENGKULU UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1704,
    provinceId: 17,
    name: "KABUPATEN KAUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1705,
    provinceId: 17,
    name: "KABUPATEN SELUMA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1706,
    provinceId: 17,
    name: "KABUPATEN MUKOMUKO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1707,
    provinceId: 17,
    name: "KABUPATEN LEBONG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1708,
    provinceId: 17,
    name: "KABUPATEN KEPAHIANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1709,
    provinceId: 17,
    name: "KABUPATEN BENGKULU TENGAH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1771,
    provinceId: 17,
    name: "KOTA BENGKULU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1801,
    provinceId: 18,
    name: "KABUPATEN LAMPUNG BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1802,
    provinceId: 18,
    name: "KABUPATEN TANGGAMUS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1803,
    provinceId: 18,
    name: "KABUPATEN LAMPUNG SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1804,
    provinceId: 18,
    name: "KABUPATEN LAMPUNG TIMUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1805,
    provinceId: 18,
    name: "KABUPATEN LAMPUNG TENGAH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1806,
    provinceId: 18,
    name: "KABUPATEN LAMPUNG UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1807,
    provinceId: 18,
    name: "KABUPATEN WAY KANAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1808,
    provinceId: 18,
    name: "KABUPATEN TULANGBAWANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1809,
    provinceId: 18,
    name: "KABUPATEN PESAWARAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1810,
    provinceId: 18,
    name: "KABUPATEN PRINGSEWU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1811,
    provinceId: 18,
    name: "KABUPATEN MESUJI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1812,
    provinceId: 18,
    name: "KABUPATEN TULANG BAWANG BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1813,
    provinceId: 18,
    name: "KABUPATEN PESISIR BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1871,
    provinceId: 18,
    name: "KOTA BANDAR LAMPUNG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1872,
    provinceId: 18,
    name: "KOTA METRO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1901,
    provinceId: 19,
    name: "KABUPATEN BANGKA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1902,
    provinceId: 19,
    name: "KABUPATEN BELITUNG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1903,
    provinceId: 19,
    name: "KABUPATEN BANGKA BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1904,
    provinceId: 19,
    name: "KABUPATEN BANGKA TENGAH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1905,
    provinceId: 19,
    name: "KABUPATEN BANGKA SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1906,
    provinceId: 19,
    name: "KABUPATEN BELITUNG TIMUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1971,
    provinceId: 19,
    name: "KOTA PANGKAL PINANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2101,
    provinceId: 21,
    name: "KABUPATEN KARIMUN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2102,
    provinceId: 21,
    name: "KABUPATEN BINTAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2103,
    provinceId: 21,
    name: "KABUPATEN NATUNA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2104,
    provinceId: 21,
    name: "KABUPATEN LINGGA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2105,
    provinceId: 21,
    name: "KABUPATEN KEPULAUAN ANAMBAS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2171,
    provinceId: 21,
    name: "KOTA B A T A M",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2172,
    provinceId: 21,
    name: "KOTA TANJUNG PINANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3101,
    provinceId: 31,
    name: "KABUPATEN KEPULAUAN SERIBU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3171,
    provinceId: 31,
    name: "KOTA JAKARTA SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3172,
    provinceId: 31,
    name: "KOTA JAKARTA TIMUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3173,
    provinceId: 31,
    name: "KOTA JAKARTA PUSAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3174,
    provinceId: 31,
    name: "KOTA JAKARTA BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3175,
    provinceId: 31,
    name: "KOTA JAKARTA UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3201,
    provinceId: 32,
    name: "KABUPATEN BOGOR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3202,
    provinceId: 32,
    name: "KABUPATEN SUKABUMI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3203,
    provinceId: 32,
    name: "KABUPATEN CIANJUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3204,
    provinceId: 32,
    name: "KABUPATEN BANDUNG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3205,
    provinceId: 32,
    name: "KABUPATEN GARUT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3206,
    provinceId: 32,
    name: "KABUPATEN TASIKMALAYA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3207,
    provinceId: 32,
    name: "KABUPATEN CIAMIS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3208,
    provinceId: 32,
    name: "KABUPATEN KUNINGAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3209,
    provinceId: 32,
    name: "KABUPATEN CIREBON",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3210,
    provinceId: 32,
    name: "KABUPATEN MAJALENGKA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3211,
    provinceId: 32,
    name: "KABUPATEN SUMEDANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3212,
    provinceId: 32,
    name: "KABUPATEN INDRAMAYU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3213,
    provinceId: 32,
    name: "KABUPATEN SUBANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3214,
    provinceId: 32,
    name: "KABUPATEN PURWAKARTA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3215,
    provinceId: 32,
    name: "KABUPATEN KARAWANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3216,
    provinceId: 32,
    name: "KABUPATEN BEKASI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3217,
    provinceId: 32,
    name: "KABUPATEN BANDUNG BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3218,
    provinceId: 32,
    name: "KABUPATEN PANGANDARAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3271,
    provinceId: 32,
    name: "KOTA BOGOR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3272,
    provinceId: 32,
    name: "KOTA SUKABUMI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3273,
    provinceId: 32,
    name: "KOTA BANDUNG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3274,
    provinceId: 32,
    name: "KOTA CIREBON",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3275,
    provinceId: 32,
    name: "KOTA BEKASI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3276,
    provinceId: 32,
    name: "KOTA DEPOK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3277,
    provinceId: 32,
    name: "KOTA CIMAHI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3278,
    provinceId: 32,
    name: "KOTA TASIKMALAYA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3279,
    provinceId: 32,
    name: "KOTA BANJAR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3301,
    provinceId: 33,
    name: "KABUPATEN CILACAP",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3302,
    provinceId: 33,
    name: "KABUPATEN BANYUMAS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3303,
    provinceId: 33,
    name: "KABUPATEN PURBALINGGA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3304,
    provinceId: 33,
    name: "KABUPATEN BANJARNEGARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3305,
    provinceId: 33,
    name: "KABUPATEN KEBUMEN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3306,
    provinceId: 33,
    name: "KABUPATEN PURWOREJO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3307,
    provinceId: 33,
    name: "KABUPATEN WONOSOBO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3308,
    provinceId: 33,
    name: "KABUPATEN MAGELANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3309,
    provinceId: 33,
    name: "KABUPATEN BOYOLALI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3310,
    provinceId: 33,
    name: "KABUPATEN KLATEN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3311,
    provinceId: 33,
    name: "KABUPATEN SUKOHARJO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3312,
    provinceId: 33,
    name: "KABUPATEN WONOGIRI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3313,
    provinceId: 33,
    name: "KABUPATEN KARANGANYAR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3314,
    provinceId: 33,
    name: "KABUPATEN SRAGEN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3315,
    provinceId: 33,
    name: "KABUPATEN GROBOGAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3316,
    provinceId: 33,
    name: "KABUPATEN BLORA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3317,
    provinceId: 33,
    name: "KABUPATEN REMBANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3318,
    provinceId: 33,
    name: "KABUPATEN PATI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3319,
    provinceId: 33,
    name: "KABUPATEN KUDUS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3320,
    provinceId: 33,
    name: "KABUPATEN JEPARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3321,
    provinceId: 33,
    name: "KABUPATEN DEMAK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3322,
    provinceId: 33,
    name: "KABUPATEN SEMARANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3323,
    provinceId: 33,
    name: "KABUPATEN TEMANGGUNG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3324,
    provinceId: 33,
    name: "KABUPATEN KENDAL",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3325,
    provinceId: 33,
    name: "KABUPATEN BATANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3326,
    provinceId: 33,
    name: "KABUPATEN PEKALONGAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3327,
    provinceId: 33,
    name: "KABUPATEN PEMALANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3328,
    provinceId: 33,
    name: "KABUPATEN TEGAL",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3329,
    provinceId: 33,
    name: "KABUPATEN BREBES",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3371,
    provinceId: 33,
    name: "KOTA MAGELANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3372,
    provinceId: 33,
    name: "KOTA SURAKARTA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3373,
    provinceId: 33,
    name: "KOTA SALATIGA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3374,
    provinceId: 33,
    name: "KOTA SEMARANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3375,
    provinceId: 33,
    name: "KOTA PEKALONGAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3376,
    provinceId: 33,
    name: "KOTA TEGAL",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3401,
    provinceId: 34,
    name: "KABUPATEN KULON PROGO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3402,
    provinceId: 34,
    name: "KABUPATEN BANTUL",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3403,
    provinceId: 34,
    name: "KABUPATEN GUNUNG KIDUL",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3404,
    provinceId: 34,
    name: "KABUPATEN SLEMAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3471,
    provinceId: 34,
    name: "KOTA YOGYAKARTA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3501,
    provinceId: 35,
    name: "KABUPATEN PACITAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3502,
    provinceId: 35,
    name: "KABUPATEN PONOROGO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3503,
    provinceId: 35,
    name: "KABUPATEN TRENGGALEK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3504,
    provinceId: 35,
    name: "KABUPATEN TULUNGAGUNG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3505,
    provinceId: 35,
    name: "KABUPATEN BLITAR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3506,
    provinceId: 35,
    name: "KABUPATEN KEDIRI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3507,
    provinceId: 35,
    name: "KABUPATEN MALANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3508,
    provinceId: 35,
    name: "KABUPATEN LUMAJANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3509,
    provinceId: 35,
    name: "KABUPATEN JEMBER",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3510,
    provinceId: 35,
    name: "KABUPATEN BANYUWANGI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3511,
    provinceId: 35,
    name: "KABUPATEN BONDOWOSO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3512,
    provinceId: 35,
    name: "KABUPATEN SITUBONDO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3513,
    provinceId: 35,
    name: "KABUPATEN PROBOLINGGO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3514,
    provinceId: 35,
    name: "KABUPATEN PASURUAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3515,
    provinceId: 35,
    name: "KABUPATEN SIDOARJO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3516,
    provinceId: 35,
    name: "KABUPATEN MOJOKERTO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3517,
    provinceId: 35,
    name: "KABUPATEN JOMBANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3518,
    provinceId: 35,
    name: "KABUPATEN NGANJUK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3519,
    provinceId: 35,
    name: "KABUPATEN MADIUN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3520,
    provinceId: 35,
    name: "KABUPATEN MAGETAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3521,
    provinceId: 35,
    name: "KABUPATEN NGAWI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3522,
    provinceId: 35,
    name: "KABUPATEN BOJONEGORO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3523,
    provinceId: 35,
    name: "KABUPATEN TUBAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3524,
    provinceId: 35,
    name: "KABUPATEN LAMONGAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3525,
    provinceId: 35,
    name: "KABUPATEN GRESIK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3526,
    provinceId: 35,
    name: "KABUPATEN BANGKALAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3527,
    provinceId: 35,
    name: "KABUPATEN SAMPANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3528,
    provinceId: 35,
    name: "KABUPATEN PAMEKASAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3529,
    provinceId: 35,
    name: "KABUPATEN SUMENEP",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3571,
    provinceId: 35,
    name: "KOTA KEDIRI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3572,
    provinceId: 35,
    name: "KOTA BLITAR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3573,
    provinceId: 35,
    name: "KOTA MALANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3574,
    provinceId: 35,
    name: "KOTA PROBOLINGGO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3575,
    provinceId: 35,
    name: "KOTA PASURUAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3576,
    provinceId: 35,
    name: "KOTA MOJOKERTO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3577,
    provinceId: 35,
    name: "KOTA MADIUN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3578,
    provinceId: 35,
    name: "KOTA SURABAYA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3579,
    provinceId: 35,
    name: "KOTA BATU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3601,
    provinceId: 36,
    name: "KABUPATEN PANDEGLANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3602,
    provinceId: 36,
    name: "KABUPATEN LEBAK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3603,
    provinceId: 36,
    name: "KABUPATEN TANGERANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3604,
    provinceId: 36,
    name: "KABUPATEN SERANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3671,
    provinceId: 36,
    name: "KOTA TANGERANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3672,
    provinceId: 36,
    name: "KOTA CILEGON",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3673,
    provinceId: 36,
    name: "KOTA SERANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3674,
    provinceId: 36,
    name: "KOTA TANGERANG SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5101,
    provinceId: 51,
    name: "KABUPATEN JEMBRANA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5102,
    provinceId: 51,
    name: "KABUPATEN TABANAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5103,
    provinceId: 51,
    name: "KABUPATEN BADUNG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5104,
    provinceId: 51,
    name: "KABUPATEN GIANYAR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5105,
    provinceId: 51,
    name: "KABUPATEN KLUNGKUNG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5106,
    provinceId: 51,
    name: "KABUPATEN BANGLI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5107,
    provinceId: 51,
    name: "KABUPATEN KARANG ASEM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5108,
    provinceId: 51,
    name: "KABUPATEN BULELENG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5171,
    provinceId: 51,
    name: "KOTA DENPASAR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5201,
    provinceId: 52,
    name: "KABUPATEN LOMBOK BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5202,
    provinceId: 52,
    name: "KABUPATEN LOMBOK TENGAH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5203,
    provinceId: 52,
    name: "KABUPATEN LOMBOK TIMUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5204,
    provinceId: 52,
    name: "KABUPATEN SUMBAWA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5205,
    provinceId: 52,
    name: "KABUPATEN DOMPU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5206,
    provinceId: 52,
    name: "KABUPATEN BIMA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5207,
    provinceId: 52,
    name: "KABUPATEN SUMBAWA BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5208,
    provinceId: 52,
    name: "KABUPATEN LOMBOK UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5271,
    provinceId: 52,
    name: "KOTA MATARAM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5272,
    provinceId: 52,
    name: "KOTA BIMA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5301,
    provinceId: 53,
    name: "KABUPATEN SUMBA BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5302,
    provinceId: 53,
    name: "KABUPATEN SUMBA TIMUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5303,
    provinceId: 53,
    name: "KABUPATEN KUPANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5304,
    provinceId: 53,
    name: "KABUPATEN TIMOR TENGAH SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5305,
    provinceId: 53,
    name: "KABUPATEN TIMOR TENGAH UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5306,
    provinceId: 53,
    name: "KABUPATEN BELU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5307,
    provinceId: 53,
    name: "KABUPATEN ALOR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5308,
    provinceId: 53,
    name: "KABUPATEN LEMBATA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5309,
    provinceId: 53,
    name: "KABUPATEN FLORES TIMUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5310,
    provinceId: 53,
    name: "KABUPATEN SIKKA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5311,
    provinceId: 53,
    name: "KABUPATEN ENDE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5312,
    provinceId: 53,
    name: "KABUPATEN NGADA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5313,
    provinceId: 53,
    name: "KABUPATEN MANGGARAI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5314,
    provinceId: 53,
    name: "KABUPATEN ROTE NDAO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5315,
    provinceId: 53,
    name: "KABUPATEN MANGGARAI BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5316,
    provinceId: 53,
    name: "KABUPATEN SUMBA TENGAH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5317,
    provinceId: 53,
    name: "KABUPATEN SUMBA BARAT DAYA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5318,
    provinceId: 53,
    name: "KABUPATEN NAGEKEO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5319,
    provinceId: 53,
    name: "KABUPATEN MANGGARAI TIMUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5320,
    provinceId: 53,
    name: "KABUPATEN SABU RAIJUA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5321,
    provinceId: 53,
    name: "KABUPATEN MALAKA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5371,
    provinceId: 53,
    name: "KOTA KUPANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6101,
    provinceId: 61,
    name: "KABUPATEN SAMBAS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6102,
    provinceId: 61,
    name: "KABUPATEN BENGKAYANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6103,
    provinceId: 61,
    name: "KABUPATEN LANDAK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6104,
    provinceId: 61,
    name: "KABUPATEN MEMPAWAH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6105,
    provinceId: 61,
    name: "KABUPATEN SANGGAU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6106,
    provinceId: 61,
    name: "KABUPATEN KETAPANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6107,
    provinceId: 61,
    name: "KABUPATEN SINTANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6108,
    provinceId: 61,
    name: "KABUPATEN KAPUAS HULU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6109,
    provinceId: 61,
    name: "KABUPATEN SEKADAU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6110,
    provinceId: 61,
    name: "KABUPATEN MELAWI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6111,
    provinceId: 61,
    name: "KABUPATEN KAYONG UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6112,
    provinceId: 61,
    name: "KABUPATEN KUBU RAYA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6171,
    provinceId: 61,
    name: "KOTA PONTIANAK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6172,
    provinceId: 61,
    name: "KOTA SINGKAWANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6201,
    provinceId: 62,
    name: "KABUPATEN KOTAWARINGIN BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6202,
    provinceId: 62,
    name: "KABUPATEN KOTAWARINGIN TIMUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6203,
    provinceId: 62,
    name: "KABUPATEN KAPUAS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6204,
    provinceId: 62,
    name: "KABUPATEN BARITO SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6205,
    provinceId: 62,
    name: "KABUPATEN BARITO UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6206,
    provinceId: 62,
    name: "KABUPATEN SUKAMARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6207,
    provinceId: 62,
    name: "KABUPATEN LAMANDAU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6208,
    provinceId: 62,
    name: "KABUPATEN SERUYAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6209,
    provinceId: 62,
    name: "KABUPATEN KATINGAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6210,
    provinceId: 62,
    name: "KABUPATEN PULANG PISAU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6211,
    provinceId: 62,
    name: "KABUPATEN GUNUNG MAS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6212,
    provinceId: 62,
    name: "KABUPATEN BARITO TIMUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6213,
    provinceId: 62,
    name: "KABUPATEN MURUNG RAYA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6271,
    provinceId: 62,
    name: "KOTA PALANGKA RAYA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6301,
    provinceId: 63,
    name: "KABUPATEN TANAH LAUT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6302,
    provinceId: 63,
    name: "KABUPATEN KOTA BARU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6303,
    provinceId: 63,
    name: "KABUPATEN BANJAR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6304,
    provinceId: 63,
    name: "KABUPATEN BARITO KUALA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6305,
    provinceId: 63,
    name: "KABUPATEN TAPIN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6306,
    provinceId: 63,
    name: "KABUPATEN HULU SUNGAI SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6307,
    provinceId: 63,
    name: "KABUPATEN HULU SUNGAI TENGAH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6308,
    provinceId: 63,
    name: "KABUPATEN HULU SUNGAI UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6309,
    provinceId: 63,
    name: "KABUPATEN TABALONG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6310,
    provinceId: 63,
    name: "KABUPATEN TANAH BUMBU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6311,
    provinceId: 63,
    name: "KABUPATEN BALANGAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6371,
    provinceId: 63,
    name: "KOTA BANJARMASIN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6372,
    provinceId: 63,
    name: "KOTA BANJAR BARU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6401,
    provinceId: 64,
    name: "KABUPATEN PASER",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6402,
    provinceId: 64,
    name: "KABUPATEN KUTAI BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6403,
    provinceId: 64,
    name: "KABUPATEN KUTAI KARTANEGARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6404,
    provinceId: 64,
    name: "KABUPATEN KUTAI TIMUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6405,
    provinceId: 64,
    name: "KABUPATEN BERAU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6409,
    provinceId: 64,
    name: "KABUPATEN PENAJAM PASER UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6411,
    provinceId: 64,
    name: "KABUPATEN MAHAKAM HULU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6471,
    provinceId: 64,
    name: "KOTA BALIKPAPAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6472,
    provinceId: 64,
    name: "KOTA SAMARINDA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6474,
    provinceId: 64,
    name: "KOTA BONTANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6501,
    provinceId: 65,
    name: "KABUPATEN MALINAU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6502,
    provinceId: 65,
    name: "KABUPATEN BULUNGAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6503,
    provinceId: 65,
    name: "KABUPATEN TANA TIDUNG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6504,
    provinceId: 65,
    name: "KABUPATEN NUNUKAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6571,
    provinceId: 65,
    name: "KOTA TARAKAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7101,
    provinceId: 71,
    name: "KABUPATEN BOLAANG MONGONDOW",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7102,
    provinceId: 71,
    name: "KABUPATEN MINAHASA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7103,
    provinceId: 71,
    name: "KABUPATEN KEPULAUAN SANGIHE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7104,
    provinceId: 71,
    name: "KABUPATEN KEPULAUAN TALAUD",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7105,
    provinceId: 71,
    name: "KABUPATEN MINAHASA SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7106,
    provinceId: 71,
    name: "KABUPATEN MINAHASA UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7107,
    provinceId: 71,
    name: "KABUPATEN BOLAANG MONGONDOW UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7108,
    provinceId: 71,
    name: "KABUPATEN SIAU TAGULANDANG BIARO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7109,
    provinceId: 71,
    name: "KABUPATEN MINAHASA TENGGARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7110,
    provinceId: 71,
    name: "KABUPATEN BOLAANG MONGONDOW SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7111,
    provinceId: 71,
    name: "KABUPATEN BOLAANG MONGONDOW TIMUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7171,
    provinceId: 71,
    name: "KOTA MANADO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7172,
    provinceId: 71,
    name: "KOTA BITUNG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7173,
    provinceId: 71,
    name: "KOTA TOMOHON",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7174,
    provinceId: 71,
    name: "KOTA KOTAMOBAGU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7201,
    provinceId: 72,
    name: "KABUPATEN BANGGAI KEPULAUAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7202,
    provinceId: 72,
    name: "KABUPATEN BANGGAI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7203,
    provinceId: 72,
    name: "KABUPATEN MOROWALI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7204,
    provinceId: 72,
    name: "KABUPATEN POSO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7205,
    provinceId: 72,
    name: "KABUPATEN DONGGALA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7206,
    provinceId: 72,
    name: "KABUPATEN TOLI-TOLI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7207,
    provinceId: 72,
    name: "KABUPATEN BUOL",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7208,
    provinceId: 72,
    name: "KABUPATEN PARIGI MOUTONG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7209,
    provinceId: 72,
    name: "KABUPATEN TOJO UNA-UNA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7210,
    provinceId: 72,
    name: "KABUPATEN SIGI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7211,
    provinceId: 72,
    name: "KABUPATEN BANGGAI LAUT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7212,
    provinceId: 72,
    name: "KABUPATEN MOROWALI UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7271,
    provinceId: 72,
    name: "KOTA PALU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7301,
    provinceId: 73,
    name: "KABUPATEN KEPULAUAN SELAYAR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7302,
    provinceId: 73,
    name: "KABUPATEN BULUKUMBA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7303,
    provinceId: 73,
    name: "KABUPATEN BANTAENG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7304,
    provinceId: 73,
    name: "KABUPATEN JENEPONTO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7305,
    provinceId: 73,
    name: "KABUPATEN TAKALAR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7306,
    provinceId: 73,
    name: "KABUPATEN GOWA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7307,
    provinceId: 73,
    name: "KABUPATEN SINJAI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7308,
    provinceId: 73,
    name: "KABUPATEN MAROS",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7309,
    provinceId: 73,
    name: "KABUPATEN PANGKAJENE DAN KEPULAUAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7310,
    provinceId: 73,
    name: "KABUPATEN BARRU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7311,
    provinceId: 73,
    name: "KABUPATEN BONE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7312,
    provinceId: 73,
    name: "KABUPATEN SOPPENG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7313,
    provinceId: 73,
    name: "KABUPATEN WAJO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7314,
    provinceId: 73,
    name: "KABUPATEN SIDENRENG RAPPANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7315,
    provinceId: 73,
    name: "KABUPATEN PINRANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7316,
    provinceId: 73,
    name: "KABUPATEN ENREKANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7317,
    provinceId: 73,
    name: "KABUPATEN LUWU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7318,
    provinceId: 73,
    name: "KABUPATEN TANA TORAJA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7322,
    provinceId: 73,
    name: "KABUPATEN LUWU UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7325,
    provinceId: 73,
    name: "KABUPATEN LUWU TIMUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7326,
    provinceId: 73,
    name: "KABUPATEN TORAJA UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7371,
    provinceId: 73,
    name: "KOTA MAKASSAR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7372,
    provinceId: 73,
    name: "KOTA PAREPARE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7373,
    provinceId: 73,
    name: "KOTA PALOPO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7401,
    provinceId: 74,
    name: "KABUPATEN BUTON",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7402,
    provinceId: 74,
    name: "KABUPATEN MUNA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7403,
    provinceId: 74,
    name: "KABUPATEN KONAWE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7404,
    provinceId: 74,
    name: "KABUPATEN KOLAKA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7405,
    provinceId: 74,
    name: "KABUPATEN KONAWE SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7406,
    provinceId: 74,
    name: "KABUPATEN BOMBANA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7407,
    provinceId: 74,
    name: "KABUPATEN WAKATOBI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7408,
    provinceId: 74,
    name: "KABUPATEN KOLAKA UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7409,
    provinceId: 74,
    name: "KABUPATEN BUTON UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7410,
    provinceId: 74,
    name: "KABUPATEN KONAWE UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7411,
    provinceId: 74,
    name: "KABUPATEN KOLAKA TIMUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7412,
    provinceId: 74,
    name: "KABUPATEN KONAWE KEPULAUAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7413,
    provinceId: 74,
    name: "KABUPATEN MUNA BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7414,
    provinceId: 74,
    name: "KABUPATEN BUTON TENGAH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7415,
    provinceId: 74,
    name: "KABUPATEN BUTON SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7471,
    provinceId: 74,
    name: "KOTA KENDARI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7472,
    provinceId: 74,
    name: "KOTA BAUBAU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7501,
    provinceId: 75,
    name: "KABUPATEN BOALEMO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7502,
    provinceId: 75,
    name: "KABUPATEN GORONTALO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7503,
    provinceId: 75,
    name: "KABUPATEN POHUWATO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7504,
    provinceId: 75,
    name: "KABUPATEN BONE BOLANGO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7505,
    provinceId: 75,
    name: "KABUPATEN GORONTALO UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7571,
    provinceId: 75,
    name: "KOTA GORONTALO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7601,
    provinceId: 76,
    name: "KABUPATEN MAJENE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7602,
    provinceId: 76,
    name: "KABUPATEN POLEWALI MANDAR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7603,
    provinceId: 76,
    name: "KABUPATEN MAMASA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7604,
    provinceId: 76,
    name: "KABUPATEN MAMUJU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7605,
    provinceId: 76,
    name: "KABUPATEN MAMUJU UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 7606,
    provinceId: 76,
    name: "KABUPATEN MAMUJU TENGAH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8101,
    provinceId: 81,
    name: "KABUPATEN MALUKU TENGGARA BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8102,
    provinceId: 81,
    name: "KABUPATEN MALUKU TENGGARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8103,
    provinceId: 81,
    name: "KABUPATEN MALUKU TENGAH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8104,
    provinceId: 81,
    name: "KABUPATEN BURU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8105,
    provinceId: 81,
    name: "KABUPATEN KEPULAUAN ARU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8106,
    provinceId: 81,
    name: "KABUPATEN SERAM BAGIAN BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8107,
    provinceId: 81,
    name: "KABUPATEN SERAM BAGIAN TIMUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8108,
    provinceId: 81,
    name: "KABUPATEN MALUKU BARAT DAYA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8109,
    provinceId: 81,
    name: "KABUPATEN BURU SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8171,
    provinceId: 81,
    name: "KOTA AMBON",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8172,
    provinceId: 81,
    name: "KOTA TUAL",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8201,
    provinceId: 82,
    name: "KABUPATEN HALMAHERA BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8202,
    provinceId: 82,
    name: "KABUPATEN HALMAHERA TENGAH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8203,
    provinceId: 82,
    name: "KABUPATEN KEPULAUAN SULA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8204,
    provinceId: 82,
    name: "KABUPATEN HALMAHERA SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8205,
    provinceId: 82,
    name: "KABUPATEN HALMAHERA UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8206,
    provinceId: 82,
    name: "KABUPATEN HALMAHERA TIMUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8207,
    provinceId: 82,
    name: "KABUPATEN PULAU MOROTAI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8208,
    provinceId: 82,
    name: "KABUPATEN PULAU TALIABU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8271,
    provinceId: 82,
    name: "KOTA TERNATE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8272,
    provinceId: 82,
    name: "KOTA TIDORE KEPULAUAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9101,
    provinceId: 91,
    name: "KABUPATEN FAKFAK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9102,
    provinceId: 91,
    name: "KABUPATEN KAIMANA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9103,
    provinceId: 91,
    name: "KABUPATEN TELUK WONDAMA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9104,
    provinceId: 91,
    name: "KABUPATEN TELUK BINTUNI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9105,
    provinceId: 91,
    name: "KABUPATEN MANOKWARI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9106,
    provinceId: 91,
    name: "KABUPATEN SORONG SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9107,
    provinceId: 91,
    name: "KABUPATEN SORONG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9108,
    provinceId: 91,
    name: "KABUPATEN RAJA AMPAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9109,
    provinceId: 91,
    name: "KABUPATEN TAMBRAUW",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9110,
    provinceId: 91,
    name: "KABUPATEN MAYBRAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9111,
    provinceId: 91,
    name: "KABUPATEN MANOKWARI SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9112,
    provinceId: 91,
    name: "KABUPATEN PEGUNUNGAN ARFAK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9171,
    provinceId: 91,
    name: "KOTA SORONG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9401,
    provinceId: 94,
    name: "KABUPATEN MERAUKE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9402,
    provinceId: 94,
    name: "KABUPATEN JAYAWIJAYA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9403,
    provinceId: 94,
    name: "KABUPATEN JAYAPURA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9404,
    provinceId: 94,
    name: "KABUPATEN NABIRE",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9408,
    provinceId: 94,
    name: "KABUPATEN KEPULAUAN YAPEN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9409,
    provinceId: 94,
    name: "KABUPATEN BIAK NUMFOR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9410,
    provinceId: 94,
    name: "KABUPATEN PANIAI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9411,
    provinceId: 94,
    name: "KABUPATEN PUNCAK JAYA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9412,
    provinceId: 94,
    name: "KABUPATEN MIMIKA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9413,
    provinceId: 94,
    name: "KABUPATEN BOVEN DIGOEL",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9414,
    provinceId: 94,
    name: "KABUPATEN MAPPI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9415,
    provinceId: 94,
    name: "KABUPATEN ASMAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9416,
    provinceId: 94,
    name: "KABUPATEN YAHUKIMO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9417,
    provinceId: 94,
    name: "KABUPATEN PEGUNUNGAN BINTANG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9418,
    provinceId: 94,
    name: "KABUPATEN TOLIKARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9419,
    provinceId: 94,
    name: "KABUPATEN SARMI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9420,
    provinceId: 94,
    name: "KABUPATEN KEEROM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9426,
    provinceId: 94,
    name: "KABUPATEN WAROPEN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9427,
    provinceId: 94,
    name: "KABUPATEN SUPIORI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9428,
    provinceId: 94,
    name: "KABUPATEN MAMBERAMO RAYA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9429,
    provinceId: 94,
    name: "KABUPATEN NDUGA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9430,
    provinceId: 94,
    name: "KABUPATEN LANNY JAYA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9431,
    provinceId: 94,
    name: "KABUPATEN MAMBERAMO TENGAH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9432,
    provinceId: 94,
    name: "KABUPATEN YALIMO",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9433,
    provinceId: 94,
    name: "KABUPATEN PUNCAK",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9434,
    provinceId: 94,
    name: "KABUPATEN DOGIYAI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9435,
    provinceId: 94,
    name: "KABUPATEN INTAN JAYA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9436,
    provinceId: 94,
    name: "KABUPATEN DEIYAI",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9471,
    provinceId: 94,
    name: "KOTA JAYAPURA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

module.exports = kabupaten;
