const provinsi = [
  { id: 11, name: "ACEH", createdAt: new Date(), updatedAt: new Date() },
  {
    id: 12,
    name: "SUMATERA UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 13,
    name: "SUMATERA BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { id: 14, name: "RIAU", createdAt: new Date(), updatedAt: new Date() },
  { id: 15, name: "JAMBI", createdAt: new Date(), updatedAt: new Date() },
  {
    id: 16,
    name: "SUMATERA SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { id: 17, name: "BENGKULU", createdAt: new Date(), updatedAt: new Date() },
  { id: 18, name: "LAMPUNG", createdAt: new Date(), updatedAt: new Date() },
  {
    id: 19,
    name: "KEPULAUAN BANGKA BELITUNG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 21,
    name: "KEPULAUAN RIAU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { id: 31, name: "DKI JAKARTA", createdAt: new Date(), updatedAt: new Date() },
  { id: 32, name: "JAWA BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 33, name: "JAWA TENGAH", createdAt: new Date(), updatedAt: new Date() },
  {
    id: 34,
    name: "DI YOGYAKARTA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { id: 35, name: "JAWA TIMUR", createdAt: new Date(), updatedAt: new Date() },
  { id: 36, name: "BANTEN", createdAt: new Date(), updatedAt: new Date() },
  { id: 51, name: "BALI", createdAt: new Date(), updatedAt: new Date() },
  {
    id: 52,
    name: "NUSA TENGGARA BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 53,
    name: "NUSA TENGGARA TIMUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 61,
    name: "KALIMANTAN BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 62,
    name: "KALIMANTAN TENGAH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 63,
    name: "KALIMANTAN SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 64,
    name: "KALIMANTAN TIMUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 65,
    name: "KALIMANTAN UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 71,
    name: "SULAWESI UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 72,
    name: "SULAWESI TENGAH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 73,
    name: "SULAWESI SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 74,
    name: "SULAWESI TENGGARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { id: 75, name: "GORONTALO", createdAt: new Date(), updatedAt: new Date() },
  {
    id: 76,
    name: "SULAWESI BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { id: 81, name: "MALUKU", createdAt: new Date(), updatedAt: new Date() },
  {
    id: 82,
    name: "MALUKU UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { id: 91, name: "PAPUA BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 94, name: "PAPUA", createdAt: new Date(), updatedAt: new Date() },
];

module.exports = provinsi;
